In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [17]:
for i in range(365*20//20):
    html = requests.get('https://finance.naver.com/item/frgn.nhn?code=005930&page={}'.format(i + 1))
    table = pd.read_html(html.text)
    if i == 0:
        data = table[2].dropna().reset_index(drop = True)
    if i > 0:
        data1 = table[2].dropna().reset_index(drop = True)
        data = pd.concat([data, data1])

In [18]:
data

            날짜        종가     전일비     등락률         거래량          기관         외국인  \
            날짜        종가     전일비     등락률         거래량        순매매량        순매매량
0   2020.07.09   52800.0   200.0  -0.38%  17054850.0    -2283249  +1,515,282
1   2020.07.08   53000.0   400.0  -0.75%  19664652.0    -1497777     -219073
2   2020.07.07   53400.0  1600.0  -2.91%  30760032.0    -4064374     -624573
3   2020.07.06   55000.0  1400.0  +2.61%  19856623.0  +4,362,954  +1,362,620
4   2020.07.03   53600.0   700.0  +1.32%  11887868.0    +991,665  +1,635,492
..         ...       ...     ...     ...         ...         ...         ...
14  2005.01.07  440500.0  5500.0  +1.26%    272369.0      -73660     +71,587
15  2005.01.06  435000.0  8000.0  -1.81%    343063.0      -56059      +3,706
16  2005.01.05  443000.0  4000.0  -0.89%    467322.0       -9961      +1,683
17  2005.01.04  447000.0  4000.0  -0.89%    280347.0      -31824     +18,352
18  2005.01.03  451000.0   500.0  +0.11%    218558.0     +32,006       -6036


            보유주수     보유율
0   3.293471e+09  55.17%
1   3.291962e+09  55.14%
2   3.291151e+09  55.13%
3   3.291696e+09  55.14%
4   3.290061e+09  55.11%
..           ...     ...
14  7.983162e+07  54.20%
15  7.976003e+07  54.15%
16  7.975297e+07  54.14%
17  7.975133e+07  54.14%
18  7.973293e+07  54.13%

[7126 rows x 9 columns]

In [11]:
data = data.reset_index(drop = True)

for i in range(len(data)):
    if float(data['등락률', '등락률'][i].replace('%', '')) < 0 :
        data['전일비','전일비'][i] = -data['전일비', '전일비'][i]

data.to_excel('samsung.xlsx')

/home/cspark/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [21]:
dfstockcode = pd.read_html('http://kind.krx.co.kr/corpgeneral/corpList.do?method=download', header=0)[0]

# 종목코드에 값을 6자리 문자열로 설정 
#    종목코드의 숫자값을 6자리 문자열로 변환
#    채우는 자리는 0으로 채우기
dfstockcode.종목코드 = dfstockcode.종목코드.map('{:06d}'.format)

# # 필요한 컬럼만으로 DataFrame을 설정
# dfstockcode = dfstockcode[['회사명', '종목코드']]

# # 컬럼명을 한글에서 영어로 변경 
# dfstockcode = dfstockcode.rename(columns={'회사명':'name', '종목코드':'code'})

In [22]:
dfstockcode

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,JS전선,005560,절연선 및 케이블 제조업,"선박선,고무선,전력선,통신선 제조",2007-11-12,12월,이익희,http://www.jscable.co.kr,충청남도
1,거북선2호,101380,NaN,운송장비(선박) 임대,2008-04-25,12월,신주선,NaN,부산광역시
2,거북선6호,114140,NaN,NaN,2009-10-01,12월,김연신,NaN,제주특별자치도
3,교보메리츠,064900,NaN,"부동산 투자,운용",2002-01-30,12월,김 상 진,NaN,서울특별시
4,국제관광공사,028780,NaN,NaN,1966-03-18,12월,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3834,툴젠,199800,자연과학 및 공학 연구개발업,"유전자가위 (유전체 교정 도구) 및 이를 이용한 유전자세포치료제, 고부가가치 가축,...",2014-06-25,12월,"김영호, 이병화(각자 대표이사)",http://www.toolgen.com,서울특별시
3835,플럼라인생명과학,222670,자연과학 및 공학 연구개발업,"강아지암치료제,돼지DNA테라피",2015-07-28,12월,김앤토니경태,http://www.plsdna.com,서울특별시
3836,피엔에이치테크,239890,기초 화학물질 제조업,"OLED완성체, OLED중간체, Pd촉매",2016-08-16,12월,현서용,http://www.phtech.co.kr,경기도
3837,한국미라클피플사,331660,기타 화학제품 제조업,"은나노스텝, 닥터오렌지 등",2019-10-28,12월,이호경,http://www.kmpc.co.kr,경기도
3838,휴벡셀,212310,의료용 기기 제조업,척추용 임플란트 등,2016-07-26,12월,"박정민, 허성규(각자대표)",http://huvexel.com,경기도